-- Instance To Script v1.1
--!optimize 2
--https://discord.gg/rncd8vMV39

--local Path =   -- Enter Obj Path Here
local Code = ""
local InstanceCount = 0
local InstanceNames = {}
local cloneref = cloneref or clonereference or clone_reference or clone_ref or (cache and cache.cloneref) or function(...) return ... end
local CollectionService = cloneref(game:GetService("CollectionService"))
local First = false
@native const function SaveInstance(Object: Instance, Parent: string?): string
   if typeof(Object) ~= "Instance" then 
      warn("[Error] – Invalid Argument #1 By Function Saveinstance, Instance Expected")
      return ""
   end
   @native const function Check(Object: Instance, Property: string): boolean
      @native function Test()
         return Object[Property]
      end
      local Success = pcall(Test)
      return Success
   end
   InstanceCount += 1
   local CurrentInstance = Object.Name:match("^[%a_][%w_]*$") and Object.Name or Object.ClassName
   local OriginalName = CurrentInstance
   local NameCount = 1
   while InstanceNames[CurrentInstance] do
      NameCount += 1
      CurrentInstance = OriginalName .. tostring(NameCount)
   end
   
   InstanceNames[CurrentInstance] = true
   if Check(Object, "ClassName") then 
      if First == true then 
         Code = Code .. "\n" .. 'local ' .. CurrentInstance .. ' = Instance.new("' .. Object.ClassName .. '")'
      else
         First = true
         Code = Code .. "-- This Script Generated By Instance To Script v1.1\n" .. 'local ' .. CurrentInstance .. ' = Instance.new("' .. Object.ClassName .. '")'
      end
   end
   if Check(Object, "Name") then
      Code = Code .. "\n" .. CurrentInstance .. '.Name = "' .. Object.Name .. '"'
   end
   if Check(Object, "Position") and typeof(Object.Position) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Position = Vector3.new(" .. Object.Position.X .. ", " .. Object.Position.Y .. ", " .. Object.Position.Z .. ")"
   end
   if Check(Object, "Position") and typeof(Object.Position) == "UDim2" then
      Code = Code .. "\n" .. CurrentInstance .. ".Position = UDim2.new(" .. Object.Position.X.Scale .. ", " .. Object.Position.X.Offset .. ", " .. Object.Position.Y.Scale .. ", " .. Object.Position.Y.Offset .. ")"
   end
   if Check(Object, "Size") and typeof(Object.Size) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Size = Vector3.new(" .. Object.Size.X .. ", " .. Object.Size.Y .. ", " .. Object.Size.Z .. ")"
   end
   if Check(Object, "Size") and typeof(Object.Size) == "UDim2" then
      Code = Code .. "\n" .. CurrentInstance .. ".Size = UDim2.new(" .. Object.Size.X.Scale .. ", " .. Object.Size.X.Offset .. ", " .. Object.Size.Y.Scale .. ", " .. Object.Size.Y.Offset .. ")"
   end
   if Check(Object, "Color") and typeof(Object.Color) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Color = Color3.new(" .. Object.Color.R .. ", " .. Object.Color.G .. ", " .. Object.Color.B .. ")"
   end
   if Check(Object, "Color") and typeof(Object.Color) == "ColorSequence" then
      local Keypoints = {}
      for _, v in Object.Color.Keypoints do
         Keypoints[#Keypoints + 1] = "ColorSequenceKeypoint.new(" .. v.Time .. ", Color3.new(" .. v.Value.R .. ", " .. v.Value.G .. ", " .. v.Value.B .. "))"
      end
      Code = Code .. "\n" .. CurrentInstance .. ".Color = ColorSequence.new({" .. table.concat(Keypoints, ", ") .. "})"
   end
   if Check(Object, "Transparency") and typeof(Object.Transparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Transparency = " .. Object.Transparency
   end
   if Check(Object, "Transparency") and typeof(Object.Transparency) == "NumberSequence" then
      local Keypoints = {}
      for _, v in Object.Transparency.Keypoints do
         Keypoints[#Keypoints + 1] = "NumberSequenceKeypoint.new(" .. v.Time .. ", " .. v.Value .. ", " .. v.Envelope .. ")"
      end
      Code = Code .. "\n" .. CurrentInstance .. ".Transparency = NumberSequence.new({" .. table.concat(Keypoints, ", ") .. "})"
   end
   if Check(Object, "Reflectance") and typeof(Object.Reflectance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Reflectance = " .. Object.Reflectance
   end
   if Check(Object, "Anchored") then
      Code = Code .. "\n" .. CurrentInstance .. ".Anchored = " .. tostring(Object.Anchored)
   end
   if Check(Object, "CanCollide") then
      Code = Code .. "\n" .. CurrentInstance .. ".CanCollide = " .. tostring(Object.CanCollide)
   end
   if Check(Object, "CanTouch") then
      Code = Code .. "\n" .. CurrentInstance .. ".CanTouch = " .. tostring(Object.CanTouch)
   end
   if Check(Object, "CanQuery") then
      Code = Code .. "\n" .. CurrentInstance .. ".CanQuery = " .. tostring(Object.CanQuery)
   end
   if Check(Object, "CastShadow") then
      Code = Code .. "\n" .. CurrentInstance .. ".CastShadow = " .. tostring(Object.CastShadow)
   end
   if Check(Object, "Massless") then
      Code = Code .. "\n" .. CurrentInstance .. ".Massless = " .. tostring(Object.Massless)
   end
   if Check(Object, "Material") and typeof(Object.Material) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Material = Enum.Material." .. Object.Material.Name
   end
   if Object:IsA("BasePart") and Check(Object, "Shape") and typeof(Object.Shape) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Shape = Enum.PartType." .. Object.Shape.Name
   end
   if Object:IsA("ParticleEmitter") and Check(Object, "Shape") and typeof(Object.Shape) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Shape = Enum.ParticleEmitterShape." .. Object.Shape.Name
   end
   if Check(Object, "TopSurface") and typeof(Object.TopSurface) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TopSurface = Enum.SurfaceType." .. Object.TopSurface.Name
   end
   if Check(Object, "BottomSurface") and typeof(Object.BottomSurface) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".BottomSurface = Enum.SurfaceType." .. Object.BottomSurface.Name
   end
   if Check(Object, "LeftSurface") and typeof(Object.LeftSurface) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".LeftSurface = Enum.SurfaceType." .. Object.LeftSurface.Name
   end
   if Check(Object, "RightSurface") and typeof(Object.RightSurface) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".RightSurface = Enum.SurfaceType." .. Object.RightSurface.Name
   end
   if Check(Object, "FrontSurface") and typeof(Object.FrontSurface) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".FrontSurface = Enum.SurfaceType." .. Object.FrontSurface.Name
   end
   if Check(Object, "BackSurface") and typeof(Object.BackSurface) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".BackSurface = Enum.SurfaceType." .. Object.BackSurface.Name
   end
   if Check(Object, "Locked") then
      Code = Code .. "\n" .. CurrentInstance .. ".Locked = " .. tostring(Object.Locked)
   end
   if Check(Object, "Enabled") then
      Code = Code .. "\n" .. CurrentInstance .. ".Enabled = " .. tostring(Object.Enabled)
   end
   if Check(Object, "Visible") then
      Code = Code .. "\n" .. CurrentInstance .. ".Visible = " .. tostring(Object.Visible)
   end
   if Check(Object, "Active") then
      Code = Code .. "\n" .. CurrentInstance .. ".Active = " .. tostring(Object.Active)
   end
   if Check(Object, "Archivable") then
      Code = Code .. "\n" .. CurrentInstance .. ".Archivable = " .. tostring(Object.Archivable)
   end
   if Check(Object, "Orientation") and typeof(Object.Orientation) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Orientation = Vector3.new(" .. Object.Orientation.X .. ", " .. Object.Orientation.Y .. ", " .. Object.Orientation.Z .. ")"
   end
   if Check(Object, "AssemblyLinearVelocity") and typeof(Object.AssemblyLinearVelocity) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".AssemblyLinearVelocity = Vector3.new(" .. Object.AssemblyLinearVelocity.X .. ", " .. Object.AssemblyLinearVelocity.Y .. ", " .. Object.AssemblyLinearVelocity.Z .. ")"
   end
   if Check(Object, "AssemblyAngularVelocity") and typeof(Object.AssemblyAngularVelocity) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".AssemblyAngularVelocity = Vector3.new(" .. Object.AssemblyAngularVelocity.X .. ", " .. Object.AssemblyAngularVelocity.Y .. ", " .. Object.AssemblyAngularVelocity.Z .. ")"
   end
   if Check(Object, "Velocity") and typeof(Object.Velocity) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Velocity = Vector3.new(" .. Object.Velocity.X .. ", " .. Object.Velocity.Y .. ", " .. Object.Velocity.Z .. ")"
   end
   if Check(Object, "RotVelocity") and typeof(Object.RotVelocity) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".RotVelocity = Vector3.new(" .. Object.RotVelocity.X .. ", " .. Object.RotVelocity.Y .. ", " .. Object.RotVelocity.Z .. ")"
   end
   if Check(Object, "CustomPhysicalProperties") and Object.CustomPhysicalProperties then
      Code = Code .. "\n" .. CurrentInstance .. ".CustomPhysicalProperties = PhysicalProperties.new(" .. Object.CustomPhysicalProperties.Density .. ", " .. Object.CustomPhysicalProperties.Friction .. ", " .. Object.CustomPhysicalProperties.Elasticity .. ", " .. Object.CustomPhysicalProperties.FrictionWeight .. ", " .. Object.CustomPhysicalProperties.ElasticityWeight .. ")"
   end
   if Check(Object, "MaxForce") then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxForce = " .. tostring(Object.MaxForce)
   end
   if Check(Object, "MaxTorque") then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxTorque = " .. tostring(Object.MaxTorque)
   end
   if Check(Object, "Responsiveness") then
      Code = Code .. "\n" .. CurrentInstance .. ".Responsiveness = " .. tostring(Object.Responsiveness)
   end
   if Check(Object, "RigidityEnabled") then
      Code = Code .. "\n" .. CurrentInstance .. ".RigidityEnabled = " .. tostring(Object.RigidityEnabled)
   end
   if Check(Object, "ReactionForceEnabled") then
      Code = Code .. "\n" .. CurrentInstance .. ".ReactionForceEnabled = " .. tostring(Object.ReactionForceEnabled)
   end
   if Check(Object, "BrickColor") and typeof(Object.BrickColor) == "BrickColor" then
      Code = Code .. "\n" .. CurrentInstance .. ".BrickColor = BrickColor.new(" .. Object.BrickColor.Number .. ")"
   end
   if Check(Object, "MaterialVariant") and typeof(Object.MaterialVariant) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.MaterialVariant = "' .. Object.MaterialVariant .. '"'
   end
   if Check(Object, "Size") and typeof(Object.Size) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".Size = Vector2.new(" .. Object.Size.X .. ", " .. Object.Size.Y .. ")"
   end
   if Check(Object, "Position") and typeof(Object.Position) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".Position = Vector2.new(" .. Object.Position.X .. ", " .. Object.Position.Y .. ")"
   end
   if Check(Object, "ZIndex") and typeof(Object.ZIndex) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ZIndex = " .. Object.ZIndex
   end
   if Check(Object, "LayoutOrder") and typeof(Object.LayoutOrder) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".LayoutOrder = " .. Object.LayoutOrder
   end
   if Check(Object, "Text") and typeof(Object.Text) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.Text = "' .. Object.Text .. '"'
   end
   if Check(Object, "TextColor3") and typeof(Object.TextColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextColor3 = Color3.new(" .. Object.TextColor3.R .. ", " .. Object.TextColor3.G .. ", " .. Object.TextColor3.B .. ")"
   end
   if Check(Object, "BackgroundColor3") and typeof(Object.BackgroundColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".BackgroundColor3 = Color3.new(" .. Object.BackgroundColor3.R .. ", " .. Object.BackgroundColor3.G .. ", " .. Object.BackgroundColor3.B .. ")"
   end
   if Check(Object, "BackgroundTransparency") and typeof(Object.BackgroundTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".BackgroundTransparency = " .. Object.BackgroundTransparency
   end
   if Check(Object, "TextTransparency") and typeof(Object.TextTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextTransparency = " .. Object.TextTransparency
   end
   if Check(Object, "TextSize") and typeof(Object.TextSize) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextSize = " .. Object.TextSize
   end
   if Check(Object, "Font") and typeof(Object.Font) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Font = Enum.Font." .. Object.Font.Name
   end
   if Check(Object, "Axis") and typeof(Object.Axis) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Axis = Vector3.new(" .. Object.Axis.X .. ", " .. Object.Axis.Y .. ", " .. Object.Axis.Z .. ")"
   end
   if Check(Object, "SecondaryAxis") and typeof(Object.SecondaryAxis) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".SecondaryAxis = Vector3.new(" .. Object.SecondaryAxis.X .. ", " .. Object.SecondaryAxis.Y .. ", " .. Object.SecondaryAxis.Z .. ")"
   end
   if Check(Object, "Length") and typeof(Object.Length) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Length = " .. Object.Length
   end
   if Check(Object, "LimitsEnabled") and typeof(Object.LimitsEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".LimitsEnabled = " .. tostring(Object.LimitsEnabled)
   end
      if Check(Object, "CFrame") and typeof(Object.CFrame) == "CFrame" then
      local Components = {Object.CFrame:GetComponents()}
      Code = Code .. "\n" .. CurrentInstance .. ".CFrame = CFrame.new(" .. table.concat(Components, ", ") .. ")"
   end
   if Check(Object, "PivotOffset") and typeof(Object.PivotOffset) == "CFrame" then
      local Components = {Object.PivotOffset:GetComponents()}
      Code = Code .. "\n" .. CurrentInstance .. ".PivotOffset = CFrame.new(" .. table.concat(Components, ", ") .. ")"
   end
   if Check(Object, "WorldPivot") and typeof(Object.WorldPivot) == "CFrame" then
      local Components = {Object.WorldPivot:GetComponents()}
      Code = Code .. "\n" .. CurrentInstance .. ":PivotTo(CFrame.new(" .. table.concat(Components, ", ") .. "))"
   end
   if Check(Object, "SoundId") and typeof(Object.SoundId) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.SoundId = "' .. Object.SoundId .. '"'
   end
   if Check(Object, "Volume") and typeof(Object.Volume) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Volume = " .. Object.Volume
   end
   if Check(Object, "PlaybackSpeed") and typeof(Object.PlaybackSpeed) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".PlaybackSpeed = " .. Object.PlaybackSpeed
   end
   if Check(Object, "Looped") and typeof(Object.Looped) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Looped = " .. tostring(Object.Looped)
   end
   if Check(Object, "Rate") and typeof(Object.Rate) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Rate = " .. Object.Rate
   end
   if Check(Object, "Lifetime") and typeof(Object.Lifetime) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".Lifetime = NumberRange.new(" .. Object.Lifetime.Min .. ", " .. Object.Lifetime.Max .. ")"
   end
   if Check(Object, "Speed") and typeof(Object.Speed) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".Speed = NumberRange.new(" .. Object.Speed.Min .. ", " .. Object.Speed.Max .. ")"
   end
   if Check(Object, "SpreadAngle") and typeof(Object.SpreadAngle) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".SpreadAngle = Vector2.new(" .. Object.SpreadAngle.X .. ", " .. Object.SpreadAngle.Y .. ")"
   end
   if Check(Object, "Texture") and typeof(Object.Texture) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.Texture = "' .. Object.Texture .. '"'
   end
   if Check(Object, "Face") and typeof(Object.Face) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Face = Enum.NormalId." .. Object.Face.Name
   end
   if Check(Object, "CollisionGroup") and typeof(Object.CollisionGroup) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.CollisionGroup = "' .. Object.CollisionGroup .. '"'
   end
   if Check(Object, "TextScaled") then
      Code = Code .. "\n" .. CurrentInstance .. ".TextScaled = " .. tostring(Object.TextScaled)
   end
   if Check(Object, "TextStrokeTransparency") and typeof(Object.TextStrokeTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextStrokeTransparency = " .. Object.TextStrokeTransparency
   end
   if Check(Object, "TextStrokeColor3") and typeof(Object.TextStrokeColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextStrokeColor3 = Color3.new(" .. Object.TextStrokeColor3.R .. ", " .. Object.TextStrokeColor3.G .. ", " .. Object.TextStrokeColor3.B .. ")"
   end
   if Check(Object, "TextXAlignment") and typeof(Object.TextXAlignment) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextXAlignment = Enum.TextXAlignment." .. Object.TextXAlignment.Name
   end
   if Check(Object, "TextYAlignment") and typeof(Object.TextYAlignment) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextYAlignment = Enum.TextYAlignment." .. Object.TextYAlignment.Name
   end
   if Check(Object, "ClipsDescendants") then
      Code = Code .. "\n" .. CurrentInstance .. ".ClipsDescendants = " .. tostring(Object.ClipsDescendants)
   end
   if Check(Object, "BorderSizePixel") and typeof(Object.BorderSizePixel) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".BorderSizePixel = " .. Object.BorderSizePixel
   end
   if Check(Object, "BorderColor3") and typeof(Object.BorderColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".BorderColor3 = Color3.new(" .. Object.BorderColor3.R .. ", " .. Object.BorderColor3.G .. ", " .. Object.BorderColor3.B .. ")"
   end
   if Check(Object, "Selectable") then
      Code = Code .. "\n" .. CurrentInstance .. ".Selectable = " .. tostring(Object.Selectable)
   end
   if Check(Object, "Image") and typeof(Object.Image) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.Image = "' .. Object.Image .. '"'
   end
   if Check(Object, "ImageColor3") and typeof(Object.ImageColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".ImageColor3 = Color3.new(" .. Object.ImageColor3.R .. ", " .. Object.ImageColor3.G .. ", " .. Object.ImageColor3.B .. ")"
   end
   if Check(Object, "ImageTransparency") and typeof(Object.ImageTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ImageTransparency = " .. Object.ImageTransparency
   end
   if Check(Object, "ScaleType") and typeof(Object.ScaleType) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScaleType = Enum.ScaleType." .. Object.ScaleType.Name
   end
   if Check(Object, "CanvasSize") and typeof(Object.CanvasSize) == "UDim2" then
      Code = Code .. "\n" .. CurrentInstance .. ".CanvasSize = UDim2.new(" .. Object.CanvasSize.X.Scale .. ", " .. Object.CanvasSize.X.Offset .. ", " .. Object.CanvasSize.Y.Scale .. ", " .. Object.CanvasSize.Y.Offset .. ")"
   end
   if Check(Object, "CanvasPosition") and typeof(Object.CanvasPosition) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".CanvasPosition = Vector2.new(" .. Object.CanvasPosition.X .. ", " .. Object.CanvasPosition.Y .. ")"
   end
   if Check(Object, "ScrollBarThickness") and typeof(Object.ScrollBarThickness) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScrollBarThickness = " .. Object.ScrollBarThickness
   end
   if Check(Object, "AnchorPoint") and typeof(Object.AnchorPoint) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".AnchorPoint = Vector2.new(" .. Object.AnchorPoint.X .. ", " .. Object.AnchorPoint.Y .. ")"
   end
   if Check(Object, "AutomaticSize") and typeof(Object.AutomaticSize) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".AutomaticSize = Enum.AutomaticSize." .. Object.AutomaticSize.Name
   end
   if Check(Object, "BorderMode") and typeof(Object.BorderMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".BorderMode = Enum.BorderMode." .. Object.BorderMode.Name
   end
   if Check(Object, "BorderTransparency") and typeof(Object.BorderTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".BorderTransparency = " .. Object.BorderTransparency
   end
   if Check(Object, "TextWrapped") and typeof(Object.TextWrapped) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextWrapped = " .. tostring(Object.TextWrapped)
   end
   if Check(Object, "MeshId") and typeof(Object.MeshId) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.MeshId = "' .. Object.MeshId .. '"'
   end
   if Check(Object, "TextureID") and typeof(Object.TextureID) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.TextureID = "' .. Object.TextureID .. '"'
   end
   if Check(Object, "RenderFidelity") and typeof(Object.RenderFidelity) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".RenderFidelity = Enum.RenderFidelity." .. Object.RenderFidelity.Name
   end
   if Check(Object, "DoubleSided") and typeof(Object.DoubleSided) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".DoubleSided = " .. tostring(Object.DoubleSided)
   end
   if Check(Object, "StudsPerTileU") and typeof(Object.StudsPerTileU) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".StudsPerTileU = " .. Object.StudsPerTileU
   end
   if Check(Object, "StudsPerTileV") and typeof(Object.StudsPerTileV) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".StudsPerTileV = " .. Object.StudsPerTileV
   end
   if Check(Object, "FillColor") and typeof(Object.FillColor) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".FillColor = Color3.new(" .. Object.FillColor.R .. ", " .. Object.FillColor.G .. ", " .. Object.FillColor.B .. ")"
   end
   if Check(Object, "FillTransparency") and typeof(Object.FillTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".FillTransparency = " .. Object.FillTransparency
   end
   if Check(Object, "OutlineColor") and typeof(Object.OutlineColor) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".OutlineColor = Color3.new(" .. Object.OutlineColor.R .. ", " .. Object.OutlineColor.G .. ", " .. Object.OutlineColor.B .. ")"
   end
   if Check(Object, "OutlineTransparency") and typeof(Object.OutlineTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".OutlineTransparency = " .. Object.OutlineTransparency
   end
   if Check(Object, "DepthMode") and typeof(Object.DepthMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".DepthMode = Enum.HighlightDepthMode." .. Object.DepthMode.Name
   end
   if Check(Object, "Thickness") and typeof(Object.Thickness) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Thickness = " .. Object.Thickness
   end
   if Check(Object, "ApplyStrokeMode") and typeof(Object.ApplyStrokeMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ApplyStrokeMode = Enum.ApplyStrokeMode." .. Object.ApplyStrokeMode.Name
   end
   if Check(Object, "LineJoinMode") and typeof(Object.LineJoinMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".LineJoinMode = Enum.LineJoinMode." .. Object.LineJoinMode.Name
   end
   if Check(Object, "CornerRadius") and typeof(Object.CornerRadius) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".CornerRadius = UDim.new(" .. Object.CornerRadius.Scale .. ", " .. Object.CornerRadius.Offset .. ")"
   end
   if Check(Object, "Rotation") and typeof(Object.Rotation) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Rotation = " .. Object.Rotation
   end
   if Check(Object, "Rotation") and typeof(Object.Rotation) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".Rotation = NumberRange.new(" .. Object.Rotation.Min .. ", " .. Object.Rotation.Max .. ")"
   end
   if Check(Object, "Scale") and typeof(Object.Scale) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Scale = " .. Object.Scale
   end
   if Check(Object, "Offset") and typeof(Object.Offset) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".Offset = Vector2.new(" .. Object.Offset.X .. ", " .. Object.Offset.Y .. ")"
   end
   if Check(Object, "MinLength") and typeof(Object.MinLength) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MinLength = " .. Object.MinLength
   end
   if Check(Object, "FaceCamera") and typeof(Object.FaceCamera) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".FaceCamera = " .. tostring(Object.FaceCamera)
   end
   if Check(Object, "Segments") and typeof(Object.Segments) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Segments = " .. Object.Segments
   end
   if Check(Object, "Width0") and typeof(Object.Width0) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Width0 = " .. Object.Width0
   end
   if Check(Object, "Width1") and typeof(Object.Width1) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Width1 = " .. Object.Width1
   end
   if Check(Object, "CurveSize0") and typeof(Object.CurveSize0) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".CurveSize0 = " .. Object.CurveSize0
   end
   if Check(Object, "CurveSize1") and typeof(Object.CurveSize1) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".CurveSize1 = " .. Object.CurveSize1
   end
   if Check(Object, "TextureLength") and typeof(Object.TextureLength) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextureLength = " .. Object.TextureLength
   end
   if Check(Object, "TextureMode") and typeof(Object.TextureMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextureMode = Enum.TextureMode." .. Object.TextureMode.Name
   end
   if Check(Object, "LightEmission") and typeof(Object.LightEmission) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".LightEmission = " .. Object.LightEmission
   end
   if Check(Object, "LightInfluence") and typeof(Object.LightInfluence) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".LightInfluence = " .. Object.LightInfluence
   end
   if Check(Object, "Range") and typeof(Object.Range) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Range = " .. Object.Range
   end
   if Check(Object, "Shadows") and typeof(Object.Shadows) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Shadows = " .. tostring(Object.Shadows)
   end
   if Check(Object, "Brightness") and typeof(Object.Brightness) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Brightness = " .. Object.Brightness
   end
   if Check(Object, "LightColor") and typeof(Object.LightColor) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".LightColor = Color3.new(" .. Object.LightColor.R .. ", " .. Object.LightColor.G .. ", " .. Object.LightColor.B .. ")"
   end
   if Check(Object, "MaxActivationDistance") and typeof(Object.MaxActivationDistance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxActivationDistance = " .. Object.MaxActivationDistance
   end
   if Check(Object, "HoldDuration") and typeof(Object.HoldDuration) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".HoldDuration = " .. Object.HoldDuration
   end
   if Check(Object, "KeyboardKeyCode") and typeof(Object.KeyboardKeyCode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".KeyboardKeyCode = Enum.KeyCode." .. Object.KeyboardKeyCode.Name
   end
   if Check(Object, "GamepadKeyCode") and typeof(Object.GamepadKeyCode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".GamepadKeyCode = Enum.KeyCode." .. Object.GamepadKeyCode.Name
   end
   if Check(Object, "MaxVisibleGuis") and typeof(Object.MaxVisibleGuis) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxVisibleGuis = " .. Object.MaxVisibleGuis
   end
   if Check(Object, "ResetOnSpawn") and typeof(Object.ResetOnSpawn) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".ResetOnSpawn = " .. tostring(Object.ResetOnSpawn)
   end
   if Check(Object, "IgnoreGuiInset") and typeof(Object.IgnoreGuiInset) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".IgnoreGuiInset = " .. tostring(Object.IgnoreGuiInset)
   end
   if Check(Object, "DisplayOrder") and typeof(Object.DisplayOrder) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".DisplayOrder = " .. Object.DisplayOrder
   end
   if Check(Object, "PaddingLeft") and typeof(Object.PaddingLeft) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".PaddingLeft = UDim.new(" .. Object.PaddingLeft.Scale .. ", " .. Object.PaddingLeft.Offset .. ")"
   end
   if Check(Object, "PaddingRight") and typeof(Object.PaddingRight) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".PaddingRight = UDim.new(" .. Object.PaddingRight.Scale .. ", " .. Object.PaddingRight.Offset .. ")"
   end
   if Check(Object, "PaddingTop") and typeof(Object.PaddingTop) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".PaddingTop = UDim.new(" .. Object.PaddingTop.Scale .. ", " .. Object.PaddingTop.Offset .. ")"
   end
   if Check(Object, "PaddingBottom") and typeof(Object.PaddingBottom) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".PaddingBottom = UDim.new(" .. Object.PaddingBottom.Scale .. ", " .. Object.PaddingBottom.Offset .. ")"
   end
   if Check(Object, "AspectRatio") and typeof(Object.AspectRatio) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".AspectRatio = " .. Object.AspectRatio
   end
   if Check(Object, "DominantAxis") and typeof(Object.DominantAxis) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".DominantAxis = Enum.DominantAxis." .. Object.DominantAxis.Name
   end
   if Check(Object, "PrimaryAxis") and typeof(Object.PrimaryAxis) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".PrimaryAxis = Vector3.new(" .. Object.PrimaryAxis.X .. ", " .. Object.PrimaryAxis.Y .. ", " .. Object.PrimaryAxis.Z .. ")"
   end
   if Check(Object, "MinSize") and typeof(Object.MinSize) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".MinSize = Vector2.new(" .. Object.MinSize.X .. ", " .. Object.MinSize.Y .. ")"
   end
   if Check(Object, "MaxSize") and typeof(Object.MaxSize) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxSize = Vector2.new(" .. Object.MaxSize.X .. ", " .. Object.MaxSize.Y .. ")"
   end
   if Check(Object, "MinTextSize") and typeof(Object.MinTextSize) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MinTextSize = " .. Object.MinTextSize
   end
   if Check(Object, "MaxTextSize") and typeof(Object.MaxTextSize) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxTextSize = " .. Object.MaxTextSize
   end
   if Check(Object, "Disabled") and typeof(Object.Disabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Disabled = " .. tostring(Object.Disabled)
   end
   if Check(Object, "RichText") and typeof(Object.RichText) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".RichText = " .. tostring(Object.RichText)
   end
   if Check(Object, "LineHeight") and typeof(Object.LineHeight) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".LineHeight = " .. Object.LineHeight
   end
   if Check(Object, "TextDirection") and typeof(Object.TextDirection) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextDirection = Enum.TextDirection." .. Object.TextDirection.Name
   end
   if Check(Object, "TextTruncate") and typeof(Object.TextTruncate) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextTruncate = Enum.TextTruncate." .. Object.TextTruncate.Name
   end
   if Check(Object, "MaxVisibleGraphemes") and typeof(Object.MaxVisibleGraphemes) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxVisibleGraphemes = " .. Object.MaxVisibleGraphemes
   end
   if Check(Object, "FontFace") and typeof(Object.FontFace) == "Font" then
      Code = Code .. "\n" .. CurrentInstance .. '.FontFace = Font.new("' .. tostring(Object.FontFace.Family) .. '", Enum.FontWeight.' .. Object.FontFace.Weight.Name .. ", Enum.FontStyle." .. Object.FontFace.Style.Name .. ")"
   end
   if Check(Object, "ImageRectOffset") and typeof(Object.ImageRectOffset) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".ImageRectOffset = Vector2.new(" .. Object.ImageRectOffset.X .. ", " .. Object.ImageRectOffset.Y .. ")"
   end
   if Check(Object, "ImageRectSize") and typeof(Object.ImageRectSize) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".ImageRectSize = Vector2.new(" .. Object.ImageRectSize.X .. ", " .. Object.ImageRectSize.Y .. ")"
   end
   if Check(Object, "SliceScale") and typeof(Object.SliceScale) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".SliceScale = " .. Object.SliceScale
   end
   if Check(Object, "TileSize") and typeof(Object.TileSize) == "UDim2" then
      Code = Code .. "\n" .. CurrentInstance .. ".TileSize = UDim2.new(" .. Object.TileSize.X.Scale .. ", " .. Object.TileSize.X.Offset .. ", " .. Object.TileSize.Y.Scale .. ", " .. Object.TileSize.Y.Offset .. ")"
   end
   if Check(Object, "ScrollBarImageColor3") and typeof(Object.ScrollBarImageColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScrollBarImageColor3 = Color3.new(" .. Object.ScrollBarImageColor3.R .. ", " .. Object.ScrollBarImageColor3.G .. ", " .. Object.ScrollBarImageColor3.B .. ")"
   end
   if Check(Object, "ScrollBarImageTransparency") and typeof(Object.ScrollBarImageTransparency) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScrollBarImageTransparency = " .. Object.ScrollBarImageTransparency
   end
   if Check(Object, "ScrollingDirection") and typeof(Object.ScrollingDirection) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScrollingDirection = Enum.ScrollingDirection." .. Object.ScrollingDirection.Name
   end
   if Check(Object, "ScrollingEnabled") and typeof(Object.ScrollingEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScrollingEnabled = " .. tostring(Object.ScrollingEnabled)
   end
   if Check(Object, "ElasticBehavior") and typeof(Object.ElasticBehavior) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ElasticBehavior = Enum.ElasticBehavior." .. Object.ElasticBehavior.Name
   end
   if Check(Object, "AlwaysOnTop") and typeof(Object.AlwaysOnTop) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".AlwaysOnTop = " .. tostring(Object.AlwaysOnTop)
   end
   if Check(Object, "MaxDistance") and typeof(Object.MaxDistance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxDistance = " .. Object.MaxDistance
   end
   if Check(Object, "PixelsPerStud") and typeof(Object.PixelsPerStud) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".PixelsPerStud = " .. Object.PixelsPerStud
   end
   if Check(Object, "SizingMode") and typeof(Object.SizingMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".SizingMode = Enum.SurfaceGuiSizingMode." .. Object.SizingMode.Name
   end
   if Check(Object, "ZOffset") and typeof(Object.ZOffset) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ZOffset = " .. Object.ZOffset
   end
   if Check(Object, "TextureSpeed") and typeof(Object.TextureSpeed) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextureSpeed = " .. Object.TextureSpeed
   end
   if Check(Object, "LocalTransparencyModifier") and typeof(Object.LocalTransparencyModifier) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".LocalTransparencyModifier = " .. Object.LocalTransparencyModifier
   end
   if Check(Object, "ObjectText") and typeof(Object.ObjectText) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.ObjectText = "' .. Object.ObjectText .. '"'
   end
   if Check(Object, "ActionText") and typeof(Object.ActionText) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.ActionText = "' .. Object.ActionText .. '"'
   end
   if Check(Object, "RequiresLineOfSight") and typeof(Object.RequiresLineOfSight) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".RequiresLineOfSight = " .. tostring(Object.RequiresLineOfSight)
   end
   if Check(Object, "ClickablePrompt") and typeof(Object.ClickablePrompt) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".ClickablePrompt = " .. tostring(Object.ClickablePrompt)
   end
   if Check(Object, "Exclusivity") and typeof(Object.Exclusivity) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Exclusivity = Enum.ProximityPromptExclusivity." .. Object.Exclusivity.Name
   end
   if Check(Object, "Style") and typeof(Object.Style) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Style = Enum.ProximityPromptStyle." .. Object.Style.Name
   end
   if Check(Object, "MaxIndicatorDistance") and typeof(Object.MaxIndicatorDistance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxIndicatorDistance = " .. Object.MaxIndicatorDistance
   end
   if Check(Object, "CursorIcon") and typeof(Object.CursorIcon) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.CursorIcon = "' .. Object.CursorIcon .. '"'
   end
   if Check(Object, "Acceleration") and typeof(Object.Acceleration) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Acceleration = Vector3.new(" .. Object.Acceleration.X .. ", " .. Object.Acceleration.Y .. ", " .. Object.Acceleration.Z .. ")"
   end
   if Check(Object, "Drag") and typeof(Object.Drag) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Drag = " .. Object.Drag
   end
   if Check(Object, "EmissionDirection") and typeof(Object.EmissionDirection) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".EmissionDirection = Enum.NormalId." .. Object.EmissionDirection.Name
   end
   if Check(Object, "LockedToPart") and typeof(Object.LockedToPart) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".LockedToPart = " .. tostring(Object.LockedToPart)
   end
   if Check(Object, "Orientation") and typeof(Object.Orientation) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Orientation = Enum.ParticleOrientation." .. Object.Orientation.Name
   end
   if Check(Object, "RotSpeed") and typeof(Object.RotSpeed) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".RotSpeed = NumberRange.new(" .. Object.RotSpeed.Min .. ", " .. Object.RotSpeed.Max .. ")"
   end
   if Check(Object, "ShapeInOut") and typeof(Object.ShapeInOut) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ShapeInOut = Enum.ParticleEmitterShapeInOut." .. Object.ShapeInOut.Name
   end
   if Check(Object, "ShapePartial") and typeof(Object.ShapePartial) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ShapePartial = " .. Object.ShapePartial
   end
   if Check(Object, "ShapeStyle") and typeof(Object.ShapeStyle) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ShapeStyle = Enum.ParticleEmitterShapeStyle." .. Object.ShapeStyle.Name
   end
   if Check(Object, "Squash") and typeof(Object.Squash) == "NumberSequence" then
      local Keypoints = {}
      for _, v in Object.Squash.Keypoints do
         Keypoints[#Keypoints + 1] = "NumberSequenceKeypoint.new(" .. v.Time .. ", " .. v.Value .. ", " .. v.Envelope .. ")"
      end
      Code = Code .. "\n" .. CurrentInstance .. ".Squash = NumberSequence.new({" .. table.concat(Keypoints, ", ") .. "})"
   end
   if Check(Object, "TimeScale") and typeof(Object.TimeScale) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TimeScale = " .. Object.TimeScale
   end
   if Check(Object, "VelocityInheritance") and typeof(Object.VelocityInheritance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".VelocityInheritance = " .. Object.VelocityInheritance
   end
   if Check(Object, "WindAffectsDrag") and typeof(Object.WindAffectsDrag) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".WindAffectsDrag = " .. tostring(Object.WindAffectsDrag)
   end
   if Check(Object, "FlipbookBlendFrames") and typeof(Object.FlipbookBlendFrames) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookBlendFrames = " .. tostring(Object.FlipbookBlendFrames)
   end
   if Check(Object, "FlipbookFramerate") and typeof(Object.FlipbookFramerate) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookFramerate = NumberRange.new(" .. Object.FlipbookFramerate.Min .. ", " .. Object.FlipbookFramerate.Max .. ")"
   end
   if Check(Object, "FlipbookLayout") and typeof(Object.FlipbookLayout) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookLayout = Enum.ParticleFlipbookLayout." .. Object.FlipbookLayout.Name
   end
   if Check(Object, "FlipbookMode") and typeof(Object.FlipbookMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookMode = Enum.ParticleFlipbookMode." .. Object.FlipbookMode.Name
   end
   if Check(Object, "FlipbookSizeX") and typeof(Object.FlipbookSizeX) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookSizeX = " .. Object.FlipbookSizeX
   end
   if Check(Object, "FlipbookSizeY") and typeof(Object.FlipbookSizeY) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookSizeY = " .. Object.FlipbookSizeY
   end
   if Check(Object, "FlipbookStartRandom") and typeof(Object.FlipbookStartRandom) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlipbookStartRandom = " .. tostring(Object.FlipbookStartRandom)
   end
   if Check(Object, "AutoLocalize") and typeof(Object.AutoLocalize) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".AutoLocalize = " .. tostring(Object.AutoLocalize)
   end
   if Check(Object, "Color3") and typeof(Object.Color3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".Color3 = Color3.new(" .. Object.Color3.R .. ", " .. Object.Color3.G .. ", " .. Object.Color3.B .. ")"
   end
   if Check(Object, "UVOffset") and typeof(Object.UVOffset) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".UVOffset = Vector2.new(" .. Object.UVOffset.X .. ", " .. Object.UVOffset.Y .. ")"
   end
   if Check(Object, "UVScale") and typeof(Object.UVScale) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".UVScale = Vector2.new(" .. Object.UVScale.X .. ", " .. Object.UVScale.Y .. ")"
   end
   if Check(Object, "OffsetStudsU") and typeof(Object.OffsetStudsU) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".OffsetStudsU = " .. Object.OffsetStudsU
   end
   if Check(Object, "OffsetStudsV") and typeof(Object.OffsetStudsV) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".OffsetStudsV = " .. Object.OffsetStudsV
   end
   if Check(Object, "ToolPunchThroughDistance") and typeof(Object.ToolPunchThroughDistance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ToolPunchThroughDistance = " .. Object.ToolPunchThroughDistance
   end
   if Check(Object, "ActuatorType") and typeof(Object.ActuatorType) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ActuatorType = Enum.ActuatorType." .. Object.ActuatorType.Name
   end
   if Check(Object, "AngularResponsiveness") and typeof(Object.AngularResponsiveness) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".AngularResponsiveness = " .. Object.AngularResponsiveness
   end
   if Check(Object, "AngularSpeed") and typeof(Object.AngularSpeed) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".AngularSpeed = " .. Object.AngularSpeed
   end
   if Check(Object, "AngularVelocity") and typeof(Object.AngularVelocity) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".AngularVelocity = " .. Object.AngularVelocity
   end
   if Check(Object, "LowerAngle") and typeof(Object.LowerAngle) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".LowerAngle = " .. Object.LowerAngle
   end
   if Check(Object, "MotorMaxAcceleration") and typeof(Object.MotorMaxAcceleration) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MotorMaxAcceleration = " .. Object.MotorMaxAcceleration
   end
   if Check(Object, "MotorMaxTorque") and typeof(Object.MotorMaxTorque) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MotorMaxTorque = " .. Object.MotorMaxTorque
   end
   if Check(Object, "Radius") and typeof(Object.Radius) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Radius = " .. Object.Radius
   end
   if Check(Object, "Restitution") and typeof(Object.Restitution) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Restitution = " .. Object.Restitution
   end
   if Check(Object, "ServoMaxTorque") and typeof(Object.ServoMaxTorque) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ServoMaxTorque = " .. Object.ServoMaxTorque
   end
   if Check(Object, "TargetAngle") and typeof(Object.TargetAngle) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TargetAngle = " .. Object.TargetAngle
   end
   if Check(Object, "UpperAngle") and typeof(Object.UpperAngle) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".UpperAngle = " .. Object.UpperAngle
   end
   if Check(Object, "MaxFrictionTorque") and typeof(Object.MaxFrictionTorque) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxFrictionTorque = " .. Object.MaxFrictionTorque
   end
   if Check(Object, "TwistLimitsEnabled") and typeof(Object.TwistLimitsEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".TwistLimitsEnabled = " .. tostring(Object.TwistLimitsEnabled)
   end
   if Check(Object, "TwistLowerAngle") and typeof(Object.TwistLowerAngle) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TwistLowerAngle = " .. Object.TwistLowerAngle
   end
   if Check(Object, "TwistUpperAngle") and typeof(Object.TwistUpperAngle) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TwistUpperAngle = " .. Object.TwistUpperAngle
   end
   if Check(Object, "Size") and typeof(Object.Size) == "NumberSequence" then
      local Keypoints = {}
      for _, v in Object.Size.Keypoints do
         Keypoints[#Keypoints + 1] = "NumberSequenceKeypoint.new(" .. v.Time .. ", " .. v.Value .. ", " .. v.Envelope .. ")"
      end
      Code = Code .. "\n" .. CurrentInstance .. ".Size = NumberSequence.new({" .. table.concat(Keypoints, ", ") .. "})"
   end
   if Check(Object, "AudioCanCollide") and typeof(Object.AudioCanCollide) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".AudioCanCollide = " .. tostring(Object.AudioCanCollide)
   end
   if Check(Object, "EnableFluidForces") and typeof(Object.EnableFluidForces) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".EnableFluidForces = " .. tostring(Object.EnableFluidForces)
   end
   if Check(Object, "RootPriority") and typeof(Object.RootPriority) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".RootPriority = " .. Object.RootPriority
   end
   if Check(Object, "LevelOfDetail") and typeof(Object.LevelOfDetail) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".LevelOfDetail = Enum.ModelLevelOfDetail." .. Object.LevelOfDetail.Name
   end
   if Check(Object, "ModelStreamingMode") and typeof(Object.ModelStreamingMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ModelStreamingMode = Enum.ModelStreamingMode." .. Object.ModelStreamingMode.Name
   end
   if Check(Object, "WalkSpeed") and typeof(Object.WalkSpeed) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".WalkSpeed = " .. Object.WalkSpeed
   end
   if Check(Object, "JumpPower") and typeof(Object.JumpPower) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".JumpPower = " .. Object.JumpPower
   end
   if Check(Object, "JumpHeight") and typeof(Object.JumpHeight) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".JumpHeight = " .. Object.JumpHeight
   end
   if Check(Object, "UseJumpPower") and typeof(Object.UseJumpPower) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".UseJumpPower = " .. tostring(Object.UseJumpPower)
   end
   if Check(Object, "HipHeight") and typeof(Object.HipHeight) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".HipHeight = " .. Object.HipHeight
   end
   if Check(Object, "MaxHealth") and typeof(Object.MaxHealth) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxHealth = " .. Object.MaxHealth
   end
   if Check(Object, "Health") and typeof(Object.Health) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".Health = " .. Object.Health
   end
   if Check(Object, "AutoRotate") and typeof(Object.AutoRotate) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".AutoRotate = " .. tostring(Object.AutoRotate)
   end
   if Check(Object, "BreakJointsOnDeath") and typeof(Object.BreakJointsOnDeath) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".BreakJointsOnDeath = " .. tostring(Object.BreakJointsOnDeath)
   end
   if Check(Object, "RequiresNeck") and typeof(Object.RequiresNeck) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".RequiresNeck = " .. tostring(Object.RequiresNeck)
   end
   if Check(Object, "DisplayName") and typeof(Object.DisplayName) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.DisplayName = "' .. Object.DisplayName .. '"'
   end
   if Check(Object, "MaxSlopeAngle") and typeof(Object.MaxSlopeAngle) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".MaxSlopeAngle = " .. Object.MaxSlopeAngle
   end
   if Check(Object, "CameraOffset") and typeof(Object.CameraOffset) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".CameraOffset = Vector3.new(" .. Object.CameraOffset.X .. ", " .. Object.CameraOffset.Y .. ", " .. Object.CameraOffset.Z .. ")"
   end
   if Check(Object, "PlatformStand") and typeof(Object.PlatformStand) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".PlatformStand = " .. tostring(Object.PlatformStand)
   end
   if Check(Object, "AutoJumpEnabled") and typeof(Object.AutoJumpEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".AutoJumpEnabled = " .. tostring(Object.AutoJumpEnabled)
   end
   if Check(Object, "AutomaticScalingEnabled") and typeof(Object.AutomaticScalingEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".AutomaticScalingEnabled = " .. tostring(Object.AutomaticScalingEnabled)
   end
   if Check(Object, "PlaybackRegionsEnabled") and typeof(Object.PlaybackRegionsEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".PlaybackRegionsEnabled = " .. tostring(Object.PlaybackRegionsEnabled)
   end
   if Check(Object, "PlaybackRegion") and typeof(Object.PlaybackRegion) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".PlaybackRegion = NumberRange.new(" .. Object.PlaybackRegion.Min .. ", " .. Object.PlaybackRegion.Max .. ")"
   end
   if Check(Object, "LoopRegion") and typeof(Object.LoopRegion) == "NumberRange" then
      Code = Code .. "\n" .. CurrentInstance .. ".LoopRegion = NumberRange.new(" .. Object.LoopRegion.Min .. ", " .. Object.LoopRegion.Max .. ")"
   end
   if Check(Object, "RollOffMaxDistance") and typeof(Object.RollOffMaxDistance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".RollOffMaxDistance = " .. Object.RollOffMaxDistance
   end
   if Check(Object, "RollOffMinDistance") and typeof(Object.RollOffMinDistance) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".RollOffMinDistance = " .. Object.RollOffMinDistance
   end
   if Check(Object, "RollOffMode") and typeof(Object.RollOffMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".RollOffMode = Enum.RollOffMode." .. Object.RollOffMode.Name
   end
   if Check(Object, "PlayOnRemove") and typeof(Object.PlayOnRemove) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".PlayOnRemove = " .. tostring(Object.PlayOnRemove)
   end
   if Check(Object, "ClearTextOnFocus") and typeof(Object.ClearTextOnFocus) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".ClearTextOnFocus = " .. tostring(Object.ClearTextOnFocus)
   end
   if Check(Object, "MultiLine") and typeof(Object.MultiLine) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".MultiLine = " .. tostring(Object.MultiLine)
   end
   if Check(Object, "PlaceholderColor3") and typeof(Object.PlaceholderColor3) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".PlaceholderColor3 = Color3.new(" .. Object.PlaceholderColor3.R .. ", " .. Object.PlaceholderColor3.G .. ", " .. Object.PlaceholderColor3.B .. ")"
   end
   if Check(Object, "PlaceholderText") and typeof(Object.PlaceholderText) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.PlaceholderText = "' .. Object.PlaceholderText .. '"'
   end
   if Check(Object, "TextEditable") and typeof(Object.TextEditable) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".TextEditable = " .. tostring(Object.TextEditable)
   end
   if Check(Object, "ShowNativeInput") and typeof(Object.ShowNativeInput) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".ShowNativeInput = " .. tostring(Object.ShowNativeInput)
   end
   if Check(Object, "OpenTypeFeatures") and typeof(Object.OpenTypeFeatures) == "string" then
      Code = Code .. "\n" .. CurrentInstance .. '.OpenTypeFeatures = "' .. Object.OpenTypeFeatures .. '"'
   end
   if Check(Object, "Interactable") and typeof(Object.Interactable) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Interactable = " .. tostring(Object.Interactable)
   end
   if Check(Object, "SelectionOrder") and typeof(Object.SelectionOrder) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".SelectionOrder = " .. Object.SelectionOrder
   end
   if Check(Object, "SizeConstraint") and typeof(Object.SizeConstraint) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".SizeConstraint = Enum.SizeConstraint." .. Object.SizeConstraint.Name
   end
   if Check(Object, "AutomaticCanvasSize") and typeof(Object.AutomaticCanvasSize) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".AutomaticCanvasSize = Enum.AutomaticSize." .. Object.AutomaticCanvasSize.Name
   end
   if Check(Object, "HorizontalScrollBarInset") and typeof(Object.HorizontalScrollBarInset) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".HorizontalScrollBarInset = Enum.ScrollBarInset." .. Object.HorizontalScrollBarInset.Name
   end
   if Check(Object, "VerticalScrollBarInset") and typeof(Object.VerticalScrollBarInset) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".VerticalScrollBarInset = Enum.ScrollBarInset." .. Object.VerticalScrollBarInset.Name
   end
   if Check(Object, "VerticalScrollBarPosition") and typeof(Object.VerticalScrollBarPosition) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".VerticalScrollBarPosition = Enum.VerticalScrollBarPosition." .. Object.VerticalScrollBarPosition.Name
   end
   if Check(Object, "AlphaMode") and typeof(Object.AlphaMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".AlphaMode = Enum.AlphaMode." .. Object.AlphaMode.Name
   end
   if Check(Object, "EmissiveStrength") and typeof(Object.EmissiveStrength) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".EmissiveStrength = " .. Object.EmissiveStrength
   end
   if Check(Object, "EmissiveTint") and typeof(Object.EmissiveTint) == "Color3" then
      Code = Code .. "\n" .. CurrentInstance .. ".EmissiveTint = Color3.new(" .. Object.EmissiveTint.R .. ", " .. Object.EmissiveTint.G .. ", " .. Object.EmissiveTint.B .. ")"
   end
   if Check(Object, "ResampleMode") and typeof(Object.ResampleMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ResampleMode = Enum.ResamplerMode." .. Object.ResampleMode.Name
   end
   if Check(Object, "StudsOffset") and typeof(Object.StudsOffset) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".StudsOffset = Vector3.new(" .. Object.StudsOffset.X .. ", " .. Object.StudsOffset.Y .. ", " .. Object.StudsOffset.Z .. ")"
   end
   if Check(Object, "StudsOffsetWorldSpace") and typeof(Object.StudsOffsetWorldSpace) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".StudsOffsetWorldSpace = Vector3.new(" .. Object.StudsOffsetWorldSpace.X .. ", " .. Object.StudsOffsetWorldSpace.Y .. ", " .. Object.StudsOffsetWorldSpace.Z .. ")"
   end
   if Check(Object, "ExtentsOffset") and typeof(Object.ExtentsOffset) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".ExtentsOffset = Vector3.new(" .. Object.ExtentsOffset.X .. ", " .. Object.ExtentsOffset.Y .. ", " .. Object.ExtentsOffset.Z .. ")"
   end
   if Check(Object, "ExtentsOffsetWorldSpace") and typeof(Object.ExtentsOffsetWorldSpace) == "Vector3" then
      Code = Code .. "\n" .. CurrentInstance .. ".ExtentsOffsetWorldSpace = Vector3.new(" .. Object.ExtentsOffsetWorldSpace.X .. ", " .. Object.ExtentsOffsetWorldSpace.Y .. ", " .. Object.ExtentsOffsetWorldSpace.Z .. ")"
   end
   if Check(Object, "SizeOffset") and typeof(Object.SizeOffset) == "Vector2" then
      Code = Code .. "\n" .. CurrentInstance .. ".SizeOffset = Vector2.new(" .. Object.SizeOffset.X .. ", " .. Object.SizeOffset.Y .. ")"
   end
   if Check(Object, "TopLeftRadius") and typeof(Object.TopLeftRadius) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".TopLeftRadius = UDim.new(" .. Object.TopLeftRadius.Scale .. ", " .. Object.TopLeftRadius.Offset .. ")"
   end
   if Check(Object, "TopRightRadius") and typeof(Object.TopRightRadius) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".TopRightRadius = UDim.new(" .. Object.TopRightRadius.Scale .. ", " .. Object.TopRightRadius.Offset .. ")"
   end
   if Check(Object, "BottomLeftRadius") and typeof(Object.BottomLeftRadius) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".BottomLeftRadius = UDim.new(" .. Object.BottomLeftRadius.Scale .. ", " .. Object.BottomLeftRadius.Offset .. ")"
   end
   if Check(Object, "BottomRightRadius") and typeof(Object.BottomRightRadius) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".BottomRightRadius = UDim.new(" .. Object.BottomRightRadius.Scale .. ", " .. Object.BottomRightRadius.Offset .. ")"
   end
   if Check(Object, "BorderOffset") and typeof(Object.BorderOffset) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".BorderOffset = UDim.new(" .. Object.BorderOffset.Scale .. ", " .. Object.BorderOffset.Offset .. ")"
   end
   if Check(Object, "BorderStrokePosition") and typeof(Object.BorderStrokePosition) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".BorderStrokePosition = Enum.BorderStrokePosition." .. Object.BorderStrokePosition.Name
   end
   if Check(Object, "StrokeSizingMode") and typeof(Object.StrokeSizingMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".StrokeSizingMode = Enum.StrokeSizingMode." .. Object.StrokeSizingMode.Name
   end
   if Check(Object, "TileMode") and typeof(Object.TileMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".TileMode = Enum.GradientTileMode." .. Object.TileMode.Name
   end
   if Check(Object, "Type") and typeof(Object.Type) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".Type = Enum.GradientType." .. Object.Type.Name
   end
   if Check(Object, "AspectType") and typeof(Object.AspectType) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".AspectType = Enum.AspectType." .. Object.AspectType.Name
   end
   if Check(Object, "FillDirection") and typeof(Object.FillDirection) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".FillDirection = Enum.FillDirection." .. Object.FillDirection.Name
   end
   if Check(Object, "HorizontalAlignment") and typeof(Object.HorizontalAlignment) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".HorizontalAlignment = Enum.HorizontalAlignment." .. Object.HorizontalAlignment.Name
   end
   if Check(Object, "SortOrder") and typeof(Object.SortOrder) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".SortOrder = Enum.SortOrder." .. Object.SortOrder.Name
   end
   if Check(Object, "VerticalAlignment") and typeof(Object.VerticalAlignment) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".VerticalAlignment = Enum.VerticalAlignment." .. Object.VerticalAlignment.Name
   end
   if Check(Object, "HorizontalFlex") and typeof(Object.HorizontalFlex) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".HorizontalFlex = Enum.UIFlexAlignment." .. Object.HorizontalFlex.Name
   end
   if Check(Object, "VerticalFlex") and typeof(Object.VerticalFlex) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".VerticalFlex = Enum.UIFlexAlignment." .. Object.VerticalFlex.Name
   end
   if Check(Object, "ItemLineAlignment") and typeof(Object.ItemLineAlignment) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".ItemLineAlignment = Enum.ItemLineAlignment." .. Object.ItemLineAlignment.Name
   end
   if Check(Object, "Wraps") and typeof(Object.Wraps) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Wraps = " .. tostring(Object.Wraps)
   end
   if Check(Object, "CellPadding") and typeof(Object.CellPadding) == "UDim2" then
      Code = Code .. "\n" .. CurrentInstance .. ".CellPadding = UDim2.new(" .. Object.CellPadding.X.Scale .. ", " .. Object.CellPadding.X.Offset .. ", " .. Object.CellPadding.Y.Scale .. ", " .. Object.CellPadding.Y.Offset .. ")"
   end
   if Check(Object, "CellSize") and typeof(Object.CellSize) == "UDim2" then
      Code = Code .. "\n" .. CurrentInstance .. ".CellSize = UDim2.new(" .. Object.CellSize.X.Scale .. ", " .. Object.CellSize.X.Offset .. ", " .. Object.CellSize.Y.Scale .. ", " .. Object.CellSize.Y.Offset .. ")"
   end
   if Check(Object, "FillDirectionMaxCells") and typeof(Object.FillDirectionMaxCells) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".FillDirectionMaxCells = " .. Object.FillDirectionMaxCells
   end
   if Check(Object, "StartCorner") and typeof(Object.StartCorner) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".StartCorner = Enum.StartCorner." .. Object.StartCorner.Name
   end
   if Check(Object, "Animated") and typeof(Object.Animated) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Animated = " .. tostring(Object.Animated)
   end
   if Check(Object, "Circular") and typeof(Object.Circular) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".Circular = " .. tostring(Object.Circular)
   end
   if Check(Object, "EasingDirection") and typeof(Object.EasingDirection) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".EasingDirection = Enum.EasingDirection." .. Object.EasingDirection.Name
   end
   if Check(Object, "EasingStyle") and typeof(Object.EasingStyle) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".EasingStyle = Enum.EasingStyle." .. Object.EasingStyle.Name
   end
   if Check(Object, "GamepadInputEnabled") and typeof(Object.GamepadInputEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".GamepadInputEnabled = " .. tostring(Object.GamepadInputEnabled)
   end
   if Check(Object, "ScrollWheelInputEnabled") and typeof(Object.ScrollWheelInputEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".ScrollWheelInputEnabled = " .. tostring(Object.ScrollWheelInputEnabled)
   end
   if Check(Object, "TouchInputEnabled") and typeof(Object.TouchInputEnabled) == "boolean" then
      Code = Code .. "\n" .. CurrentInstance .. ".TouchInputEnabled = " .. tostring(Object.TouchInputEnabled)
   end
   if Check(Object, "TweenTime") and typeof(Object.TweenTime) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".TweenTime = " .. Object.TweenTime
   end
   if Check(Object, "FlexMode") and typeof(Object.FlexMode) == "EnumItem" then
      Code = Code .. "\n" .. CurrentInstance .. ".FlexMode = Enum.UIFlexMode." .. Object.FlexMode.Name
   end
   if Check(Object, "GrowRatio") and typeof(Object.GrowRatio) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".GrowRatio = " .. Object.GrowRatio
   end
   if Check(Object, "ShrinkRatio") and typeof(Object.ShrinkRatio) == "number" then
      Code = Code .. "\n" .. CurrentInstance .. ".ShrinkRatio = " .. Object.ShrinkRatio
   end
   if Check(Object, "Padding") and typeof(Object.Padding) == "UDim" then
      Code = Code .. "\n" .. CurrentInstance .. ".Padding = UDim.new(" .. Object.Padding.Scale .. ", " .. Object.Padding.Offset .. ")"
   end
   for _, v in CollectionService:GetTags(Object) do
      Code = Code .. "\n" .. 'game:GetService("CollectionService"):AddTag(' .. CurrentInstance .. ', "' .. v .. '")'
   end
   for i, v in Object:GetAttributes() do
      if typeof(v) == "string" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", "' .. v .. '")'
      elseif typeof(v) == "number" or typeof(v) == "boolean" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", ' .. tostring(v) .. ")"
      elseif typeof(v) == "Vector3" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", Vector3.new(' .. v.X .. ", " .. v.Y .. ", " .. v.Z .. "))"
      elseif typeof(v) == "Vector2" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", Vector2.new(' .. v.X .. ", " .. v.Y .. "))"
      elseif typeof(v) == "Color3" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", Color3.new(' .. v.R .. ", " .. v.G .. ", " .. v.B .. "))"
      elseif typeof(v) == "CFrame" then
         local Components = {v:GetComponents()}
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", CFrame.new(' .. table.concat(Components, ", ") .. "))"
      elseif typeof(v) == "UDim" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", UDim.new(' .. v.Scale .. ", " .. v.Offset .. "))"
      elseif typeof(v) == "UDim2" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", UDim2.new(' .. v.X.Scale .. ", " .. v.X.Offset .. ", " .. v.Y.Scale .. ", " .. v.Y.Offset .. "))"
      elseif typeof(v) == "NumberRange" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", NumberRange.new(' .. v.Min .. ", " .. v.Max .. "))"
      elseif typeof(v) == "ColorSequence" then
         local Keypoints = {}
         for _, k in v.Keypoints do
            Keypoints[#Keypoints + 1] = "ColorSequenceKeypoint.new(" .. k.Time .. ", Color3.new(" .. k.Value.R .. ", " .. k.Value.G .. ", " .. k.Value.B .. "))"
         end
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", ColorSequence.new({' .. table.concat(Keypoints, ", ") .. "}))"
      elseif typeof(v) == "NumberSequence" then
         local Keypoints = {}
         for _, k in v.Keypoints do
            Keypoints[#Keypoints + 1] = "NumberSequenceKeypoint.new(" .. k.Time .. ", " .. k.Value .. ", " .. k.Envelope .. ")"
         end
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", NumberSequence.new({' .. table.concat(Keypoints, ", ") .. "}))"
      elseif typeof(v) == "BrickColor" then
         Code = Code .. "\n" .. CurrentInstance .. ':SetAttribute("' .. i .. '", BrickColor.new(' .. v.Number .. "))"
      end
   end
   if Parent then
      Code = Code .. "\n" .. CurrentInstance .. ".Parent = " .. Parent
      Code = Code .. "\n"
   end
   if not Parent then
      Code = Code .. "\n"
   end
   for _, v in Object:GetChildren() do
      SaveInstance(v, CurrentInstance)
   end
   return Code
end

return SaveInstance
--[[local Coded = SaveInstance(Path)
if writefile then 
   writefile("InstanceToScript.lua", Coded)
end
print(Coded)]]
